### ISSUE TITLE
Setup qwc on Windows

### ISSUE THREAD

**Issue by UserGis** [qgis/qwc2-demo-app#168]
Hi. I am trying to setup qwc on Windows and Visual code.  I get the code from git but when I try to start qwc this error  occurs:

 ```
yarn start
yarn run v1.19.1
$ npm run tsupdate && npm run themesconfig && npm run iconfont && webpack-dev-server --progress --colors --host 0.0.0.0 --port 8081

> QWC2App@1.1.0 tsupdate C:\QGIS REACT\qwc2-demo-app
> node qwc2/scripts/updateTranslations.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\QGIS REACT\qwc2-demo-app\qwc2\scripts\updateTranslations.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! QWC2App@1.1.0 tsupdate: `node qwc2/scripts/updateTranslations.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the QWC2App@1.1.0 tsupdate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-10-29T15_52_46_501Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\QGIS REACT\qwc2-demo-app> 
```

**Comment by manisandro** [comment]
Possibly the space in the path

    C:\QGIS REACT\qwc2-demo-app\qwc2\scripts\updateTranslations.js
           ^

causing troubles?

**Comment by UserGis** [comment]
I change folder to C:\QGISREACT\qwc2-demo-app\qwc2\scripts\updateTranslations.js, but I get same error.

**Comment by manisandro** [comment]
Closing since unlikely a QWC2 issue but a problem with the user's environment.

**Comment by manisandro** [comment]
(Actually what pretty likely happened here is that qwc2-demo-app was not cloned recursively, fix by

    $ git submodule init
    $ git pull --recurse-submodules

or just do

    $ git clone --recursive https://github.com/qgis/qwc2-demo-app.git

as specified in the manual)
