### ISSUE TITLE
error when running yarn start

### ISSUE THREAD

**Issue by reginaldc** [qgis/qwc2-demo-app#184]
When I run yarn start I get following error:

I get this error on Windows 7 as well as on Ubuntu eoan

Error: Cannot find module '/home/reginald/dev/qwc2/qwc2-demo-app-release_1_0/qwc2/scripts/updateTranslations.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! QWC2App@1.0.0 tsupdate: `node qwc2/scripts/updateTranslations.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the QWC2App@1.0.0 tsupdate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 

I get this error on Windows 7 as well as on Ubuntu eoan

**Comment by manisandro** [comment]
You most likely didn't clone recursively, see [1].

[1] https://github.com/qgis/qwc2-demo-app/blob/master/doc/QWC2_Documentation.md#quick-start

**Comment by reginaldc** [comment]
I used the following command:
git clone --recursive https://github.com/qgis/qwc2-demo-app.git

**Comment by manisandro** [comment]
And does `qwc2/scripts/updateTranslations.js` exist in the tree you cloned?

**Comment by reginaldc** [comment]
I forgot to install the qwc web client. I just install the demo app.
Sorry for the noise.
It works now.
Beautiful project by the way.

Regards,
