### ISSUE TITLE
yarn run prod gives error (again as #53) webpack missing?

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#214]
Hello, my system is:
```
Debian 10
yarn 1.22.4
npm 6.13.4
```
but I cannot run yarn run prod, since the error is the same of #53.
I've already did `yarn install` (and `yarn upgrade`):
```
/var/www/test/qwc2-demo-app# yarn run prod
yarn run v1.22.4
$ node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\scripts\package-commands.bat prod || ./qwc2/scripts/package-commands.sh prod

> QWC2App@1.1.0 build /var/www/mercati2/qwc2-demo-app
> node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\scripts\package-commands.bat build || ./qwc2/scripts/package-commands.sh build

> QWC2App@1.1.0 clean /var/www/mercati2/qwc2-demo-app
> rimraf dist

> QWC2App@1.1.0 iconfont /var/www/mercati2/qwc2-demo-app
> node qwc2/scripts/makeIconkit.js

Done!
./qwc2/scripts/package-commands.sh: row 10: 31150 Killed                  NODE_ENV='production' webpack
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! QWC2App@1.1.0 build: `node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\scripts\package-commands.bat build || ./qwc2/scripts/package-commands.sh build`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the QWC2App@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-01T15_34_02_167Z-debug.log
error Command failed with exit code 137.
```
Trying to run ```./qwc2/scripts/package-commands.sh build```:
```
> QWC2App@1.1.0 clean /var/www/mercati2/qwc2-demo-app
> rimraf dist


> QWC2App@1.1.0 iconfont /var/www/mercati2/qwc2-demo-app
> node qwc2/scripts/makeIconkit.js

Done!
./qwc2/scripts/package-commands.sh: riga 8: webpack: command not found
```

**Comment by manisandro** [comment]
What does the full log (i.e. `/root/.npm/_logs/2020-06-01T15_34_02_167Z-debug.log` in the output above) show? Running `package-commands.sh` directly is not expected to work unless you manually add the path to `webpack` to the `PATH`.

**Comment by lucamanga** [comment]
```
$ cat  /root/.npm/_logs/2020-06-01T15_34_02_167Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle QWC2App@1.1.0~prebuild: QWC2App@1.1.0
6 info lifecycle QWC2App@1.1.0~build: QWC2App@1.1.0
7 verbose lifecycle QWC2App@1.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle QWC2App@1.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/mercati2/qwc2-demo-app/node_modules/.bin:/usr/bin:/tmp/yarn--1591025599523-0.8426651898989654:/var/www/mercati2/qwc2-demo-app/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/var/www/mercati2/qwc2-demo-app/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle QWC2App@1.1.0~build: CWD: /var/www/mercati2/qwc2-demo-app
10 silly lifecycle QWC2App@1.1.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   `node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\\scripts\\package-commands.bat build || ./qwc2/scripts/package-commands.sh build`
10 silly lifecycle ]
11 silly lifecycle QWC2App@1.1.0~build: Returned: code: 137  signal: null
12 info lifecycle QWC2App@1.1.0~build: Failed to exec build script
13 verbose stack Error: QWC2App@1.1.0 build: `node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\scripts\package-commands.bat build || ./qwc2/scripts/package-commands.sh build`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid QWC2App@1.1.0
15 verbose cwd /var/www/mercati2/qwc2-demo-app
16 verbose Linux 4.19.0-8-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 137
22 error QWC2App@1.1.0 build: `node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\scripts\package-commands.bat build || ./qwc2/scripts/package-commands.sh build`
22 error Exit status 137
23 error Failed at the QWC2App@1.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by lucamanga** [comment]
Restarting the machine resolved the issue...
