### ISSUE TITLE
Impossible to run yarn run prod (again...)

### ISSUE THREAD

**Issue by lucamanga** [qgis/qwc2-demo-app#232]
I followed your install instructions from beginning.

I am using latest version of yarn 1.22.5 and nodejs 14.

But at 'yarn run prod' step, it complains:

```
(node:12615) V8: /var/www/qwc2/qwc2-demo-app/node_modules/ttf2woff2/jssrc/ttf2woff2.js:3 Invalid asm.js: Invalid member of stdlib
(Use `node --trace-warnings ...` to show where the warning was created)
Done!
Running webpack, this may take some time...
./qwc2/scripts/package-commands.sh: riga 11: 12628 Ucciso                  NODE_ENV='production' webpack
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! QWC2App@1.1.0 build: `node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\scripts\package-commands.bat build || ./qwc2/scripts/package-commands.sh build`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the QWC2App@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-02T12_25_32_807Z-debug.log
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by manisandro** [comment]
I also see the `asm.js` warning, but the prod build still completes (nodejs-14.7.0). What dos the complete log show?

**Comment by lucamanga** [comment]
The debug log is here:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.8
3 info using node@v14.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle QWC2App@1.1.0~prebuild: QWC2App@1.1.0
6 info lifecycle QWC2App@1.1.0~build: QWC2App@1.1.0
7 verbose lifecycle QWC2App@1.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle QWC2App@1.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/qwc2/qwc2-demo-app/node_modules/.bin:/usr/bin:/tmp/yarn--1599049494249-0.11058596301655088:/var/www/qwc2/qwc2-demo-app/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/var/www/qwc2/qwc2-demo-app/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle QWC2App@1.1.0~build: CWD: /var/www/qwc2/qwc2-demo-app
10 silly lifecycle QWC2App@1.1.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   `node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\\scripts\\package-commands.bat build || ./qwc2/scripts/package-commands.sh build`
10 silly lifecycle ]
11 silly lifecycle QWC2App@1.1.0~build: Returned: code: 137  signal: null
12 info lifecycle QWC2App@1.1.0~build: Failed to exec build script
13 verbose stack Error: QWC2App@1.1.0 build: `node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\scripts\package-commands.bat build || ./qwc2/scripts/package-commands.sh build`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid QWC2App@1.1.0
15 verbose cwd /var/www/qwc2/qwc2-demo-app
16 verbose Linux 4.19.0-9-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v14.9.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 137
22 error QWC2App@1.1.0 build: `node -e "process.exit(require('os').platform() === 'win32' ? 0 : 1)" && qwc2\scripts\package-commands.bat build || ./qwc2/scripts/package-commands.sh build`
22 error Exit status 137
23 error Failed at the QWC2App@1.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by lucamanga** [comment]
Could you write the system requirements (OS, yarn, node versions...)?

I'm using Debian 10 Buster

**Comment by manisandro** [comment]
There aren't really any specific known system requirements. If this is something that you have started hitting recently, I'd look at the apt upgrade log and see if any possible related has been updated recently and try reverting that update.

**Comment by lucamanga** [comment]
with a new ubuntu 20.04 machine, it compiled. I hope that it will compile forever :-)
