### ISSUE TITLE
ERROR reading WMS GetProjectSettings of http://qwc2.sourcepole.ch/ows/uster/bauprojekte

### ISSUE THREAD

**Issue by Lord-AY** [qgis/qwc2-demo-app#328]
Steps to replicate the issue

1.  `$ git clone --recursive https://github.com/qgis/qwc2-demo-app.git`
2. `cd qwc2-demo-app`
3. `yarn install`
4. `yarn start`

Output
```
PS C:\Users\ACER\Desktop\Front End\Node\qwc2-demo-app> yarn start
yarn run v1.13.0
$ npm run tsupdate && npm run themesconfig && npm run iconfont && webpack serve --mode development --progress --host 0.0.0.0 --port 8081

> QWC2App@2021.11.24 tsupdate C:\Users\ACER\Desktop\Front End\Node\qwc2-demo-app
> node qwc2/scripts/updateTranslations.js

Generating translations for qwc2
Wrote qwc2/translations/de-DE.json
Wrote qwc2/translations/de-CH.json
Wrote qwc2/translations/en-US.json
Wrote qwc2/translations/es-ES.json
Wrote qwc2/translations/fr-FR.json
Wrote qwc2/translations/fi-FI.json
Wrote qwc2/translations/hu-HU.json
Wrote qwc2/translations/it-IT.json
Wrote qwc2/translations/pl-PL.json
Wrote qwc2/translations/pt-BR.json
Wrote qwc2/translations/pt-PT.json
Wrote qwc2/translations/ro-RO.json
Wrote qwc2/translations/ru-RU.json
Wrote qwc2/translations/sv-SE.json
Wrote qwc2/translations/tr-TR.json
Wrote qwc2/translations/cs-CZ.json
Wrote qwc2/translations/no-NO.json
Wrote qwc2/translations/ca-ES.json
Wrote static/translations/de-DE.json
Wrote static/translations/de-CH.json
Wrote static/translations/en-US.json
Wrote static/translations/es-ES.json
Wrote static/translations/fr-FR.json
Wrote static/translations/it-IT.json
Wrote static/translations/pl-PL.json
Wrote static/translations/pt-BR.json
Wrote static/translations/pt-PT.json
Wrote static/translations/ro-RO.json
Wrote static/translations/ru-RU.json
Wrote static/translations/sv-SE.json
Wrote static/translations/tr-TR.json
Wrote static/translations/cs-CZ.json

> QWC2App@2021.11.24 themesconfig C:\Users\ACER\Desktop\Front End\Node\qwc2-demo-app
> node qwc2/scripts/themesConfig.js

Reading themesConfig.json
ERROR reading WMS GetProjectSettings of http://qwc2.sourcepole.ch/ows/uster/bauprojekte:
 Error: Request failed with status code 404
    at createError (C:\Users\ACER\Desktop\Front End\Node\qwc2-demo-app\qwc2\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\ACER\Desktop\Front End\Node\qwc2-demo-app\qwc2\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\ACER\Desktop\Front End\Node\qwc2-demo-app\qwc2\node_modules\axios\lib\adapters\http.js:293:11)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.23.0'
    },
    proxy: null,
    method: 'get',
    url: 'http://qwc2.sourcepole.ch/ows/uster/bauprojekte?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'qwc2.sourcepole.ch',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 9,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /ows/uster/bauprojekte?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.23.0\r\n' +
      'Host: qwc2.sourcepole.ch\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 2,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/ows/uster/bauprojekte?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://qwc2.sourcepole.ch/ows/uster/bauprojekte?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'qwc2.sourcepole.ch',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://qwc2.sourcepole.ch/ows/uster/bauprojekte?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      server: 'nginx/1.18.0',
      date: 'Thu, 10 Mar 2022 09:08:31 GMT',
      'content-type': 'text/html',
      'content-length': '153',
      connection: 'close'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      proxy: null,
      method: 'get',
      url: 'http://qwc2.sourcepole.ch/ows/uster/bauprojekte?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /ows/uster/bauprojekte?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.23.0\r\n' +
        'Host: qwc2.sourcepole.ch\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/ows/uster/bauprojekte?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'qwc2.sourcepole.ch',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<html>\r\n' +
      '<head><title>404 Not Found</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>404 Not Found</h1></center>\r\n' +
      '<hr><center>nginx/1.18.0</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
ERROR: Could not read GetProjectSettings
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! QWC2App@2021.11.24 themesconfig: `node qwc2/scripts/themesConfig.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the QWC2App@2021.11.24 themesconfig script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by manisandro** [comment]
Yep qwc2.sourcepole.ch is currently down, @HusseinKabbout is fixing it.

**Comment by HusseinKabbout** [comment]
`qwc2.sourcepole.ch` should be up and running again.
